### ISSUE TITLE
abrt-applet: Crash when no command line available

### ISSUE THREAD

**Issue by maage** [abrt/abrt#1372]
https://github.com/abrt/abrt/blob/1f42ed82f35a690fbad1e5e2d6629866f66e0ef2/src/applet/abrt-applet-application.c#L717

System is Fedora 29, but as version is about the same as master here, I've reported problem here.

```
$ rpm -qf /usr/bin/abrt-applet
abrt-gui-2.12.0-2.fc29.x86_64
```

```
# coredumpctl debug abrt-applet
           PID: 2108 (abrt-applet)
...
        Signal: 11 (SEGV)
     Timestamp: Tue 2019-04-02 15:32:08 EEST (31min ago)
  Command Line: /usr/bin/abrt-applet --gapplication-service
    Executable: /usr/bin/abrt-applet
...
       Storage: /var/lib/systemd/coredump/core.abrt-applet.1972.24bdf90406214cd0bd1f6b61fa3b8ae9.2108.1554208328000000.lz4
...
                
                Stack trace of thread 2108:
                #0  0x00007fe9666f703b problem_get_argv0 (libreport-gtk.so.0)
                #1  0x000055a39af5ad62 n/a (abrt-applet)
                #2  0x000055a39af5b271 n/a (abrt-applet)
                #3  0x000055a39af5c45f n/a (abrt-applet)
                #4  0x00007fe9664973dd g_closure_invoke (libgobject-2.0.so.0)
                #5  0x00007fe9664aab26 signal_emit_unlocked_R (libgobject-2.0.so.0)
                #6  0x00007fe9664b3aaa g_signal_emit_valist (libgobject-2.0.so.0)
                #7  0x00007fe9664b40a3 g_signal_emit (libgobject-2.0.so.0)
                #8  0x00007fe9665850d2 g_application_register (libgio-2.0.so.0)
                #9  0x00007fe96658570a g_application_real_local_command_line (libgio-2.0.so.0)
                #10 0x00007fe966585c8f g_application_run (libgio-2.0.so.0)
                #11 0x000055a39af5a2fc n/a (abrt-applet)
                #12 0x00007fe9661a9413 __libc_start_main (libc.so.6)
                #13 0x000055a39af5a34e n/a (abrt-applet)
                
                Stack trace of thread 2114:
                #0  0x00007fe966277421 __GI___poll (libc.so.6)
                #1  0x00007fe9663b53a6 g_main_context_poll (libglib-2.0.so.0)
                #2  0x00007fe9663b5762 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007fe9665b310a gdbus_shared_thread_func (libgio-2.0.so.0)
                #4  0x00007fe9663de2aa g_thread_proxy (libglib-2.0.so.0)
                #5  0x00007fe96584f58e start_thread (libpthread.so.0)
                #6  0x00007fe9662826a3 __clone (libc.so.6)
                
                Stack trace of thread 2130:
                #0  0x00007fe966277421 __GI___poll (libc.so.6)
                #1  0x00007fe9663b53a6 g_main_context_poll (libglib-2.0.so.0)
                #2  0x00007fe9663b54d0 g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fe96719bc7d n/a (libdconfsettings.so)
                #4  0x00007fe9663de2aa g_thread_proxy (libglib-2.0.so.0)
                #5  0x00007fe96584f58e start_thread (libpthread.so.0)
                #6  0x00007fe9662826a3 __clone (libc.so.6)
                
                Stack trace of thread 2113:
                #0  0x00007fe966277421 __GI___poll (libc.so.6)
                #1  0x00007fe9663b53a6 g_main_context_poll (libglib-2.0.so.0)
                #2  0x00007fe9663b54d0 g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007fe9663b5521 glib_worker_main (libglib-2.0.so.0)
                #4  0x00007fe9663de2aa g_thread_proxy (libglib-2.0.so.0)
                #5  0x00007fe96584f58e start_thread (libpthread.so.0)
                #6  0x00007fe9662826a3 __clone (libc.so.6)

<snip>

Core was generated by `/usr/bin/abrt-applet --gapplication-service'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fe9666f703b in problem_get_argv0 (cmdline=<optimized out>) at desktop-utils.c:31
31	desktop-utils.c: No such file or directory.
[Current thread is 1 (Thread 0x7fe964960c40 (LWP 2108))]
(gdb) where
#0  0x00007fe9666f703b in problem_get_argv0 (cmdline=<optimized out>) at desktop-utils.c:31
#1  0x000055a39af5ad62 in notify_problem_list (problems=<optimized out>) at abrt-applet-application.c:717
#2  0x000055a39af5b271 in show_problem_list_notification (problems=0x55a39c61cc60) at abrt-applet-application.c:988
#3  0x000055a39af5c45f in process_new_dirs () at abrt-applet-application.c:1151
#4  abrt_applet_application_startup (application=0x55a39c59b0a0) at abrt-applet-application.c:1211
#5  0x00007fe9664973dd in g_closure_invoke (closure=0x55a39c5cf430, return_value=0x0, n_param_values=1, 
    param_values=0x7ffddb318ad0, invocation_hint=0x7ffddb318a50) at gclosure.c:810
#6  0x00007fe9664aab26 in signal_emit_unlocked_R (node=node@entry=0x55a39c58e470, detail=detail@entry=0, 
    instance=instance@entry=0x55a39c59b0a0, emission_return=emission_return@entry=0x0, 
    instance_and_params=instance_and_params@entry=0x7ffddb318ad0) at gsignal.c:3565
#7  0x00007fe9664b3aaa in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, 
    detail=<optimized out>, var_args=var_args@entry=0x7ffddb318c90) at gsignal.c:3391
#8  0x00007fe9664b40a3 in g_signal_emit (instance=instance@entry=0x55a39c59b0a0, signal_id=<optimized out>, 
    detail=detail@entry=0) at gsignal.c:3447
#9  0x00007fe9665850d2 in g_application_register (error=0x7ffddb318dc8, cancellable=0x0, application=0x55a39c59b0a0)
    at gapplication.c:2137
#10 g_application_register (application=0x55a39c59b0a0, cancellable=0x0, error=0x7ffddb318dc8) at gapplication.c:2109
#11 0x00007fe96658570a in g_application_real_local_command_line (application=0x55a39c59b0a0, arguments=0x7ffddb318ec8, 
    exit_status=0x7ffddb318ec4) at gapplication.c:1086
#12 0x00007fe966585c8f in g_application_run (application=application@entry=0x55a39c59b0a0, argc=argc@entry=2, 
    argv=argv@entry=0x7ffddb319018) at gapplication.c:2439
#13 0x000055a39af5a2fc in main (argc=2, argv=0x7ffddb319018) at abrt-applet-main.c:24
```

As abrt_applet_problem_info_get_command_line is essentially:
```
problem_data_get_content_or_NULL (self->problem_data, FILENAME_CMDLINE)
```
It should be able to handle situation where data is NULL.

```
(gdb) print problem_info
$1 = (AbrtAppletProblemInfo_autoptr) 0x7fe948005c00
(gdb) print *problem_info
$2 = {parent_instance = {g_type_instance = {g_class = 0x55a39c5cef00}, ref_count = 1, qdata = 0x0}, 
  problem_data = 0x55a39c59f360, foreign = false, count = 1, packaged = false, envp = 0x0, pid = -1, known = false, 
  reported = false, announced = false, writable = false, time = 1554207979}
(gdb) print *problem_info->problem_data
$3 = {size = 8, mod = 7, mask = 7, nnodes = 7, noccupied = 7, keys = 0x55a39c61cbb0, hashes = 0x55a39c586cf0, 
  values = 0x7fe94800ed40, hash_func = 0x7fe9663a4170 <g_str_hash>, key_equal_func = 0x7fe9663a4150 <g_str_equal>, 
  ref_count = 1, version = 7, key_destroy_func = 0x7fe96620c0d0 <__GI___libc_free>, 
  value_destroy_func = 0x7fe9666ca7d0 <free_problem_item>}
```
And when I iterate over keys:
```
$12 = 0x0
(gdb) print (char*)problem_info->problem_data->keys[0]
$13 = 0x0
(gdb) print (char*)problem_info->problem_data->keys[1]
$14 = 0x55a39c5faf20 "uid"
(gdb) print (char*)problem_info->problem_data->keys[2]
$15 = 0x7fe94800ada0 "Directory"
(gdb) print (char*)problem_info->problem_data->keys[3]
$16 = 0x55a39c5cb820 "uuid"
(gdb) print (char*)problem_info->problem_data->keys[4]
$17 = 0x55a39c5e15c0 "count"
(gdb) print (char*)problem_info->problem_data->keys[5]
$18 = 0x55a39c5d1b10 "component"
(gdb) print (char*)problem_info->problem_data->keys[6]
$19 = 0x55a39c5d8de0 "duphash"
(gdb) print (char*)problem_info->problem_data->keys[7]
$20 = 0x55a39c5c0870 "time"
(gdb) print (char*)problem_info->problem_data->keys[8]
$21 = 0x0
...
(gdb) print *(struct problem_item *)problem_info->problem_data->values[2]
$34 = {content = 0x55a39c6248f0 "/var/spool/abrt/xorg-2019-04-02-15:26:19.731718-962", flags = 10, 
  size = 18446744073709551615, selected_by_user = 0, allowed_by_reporter = 0, default_by_reporter = 0, 
  required_by_reporter = 0}
```
So there is no cmdline.

It was this originally, but I have since deleted it. As you can see there is no cmdline.
```
% abrt-cli ls
id 5d550c36851347db669faa664ed44097f04b0a15
reason:         OsLookupColor(): Display server crashed
time:           Tue 02 Apr 2019 03:26:19 PM EEST
package:        xorg-x11-server-Xwayland-1.20.4-1.fc29
uid:            0 (root)
count:          1
Directory:      /var/spool/abrt/xorg-2019-04-02-15:26:19.731718-962
```

**Comment by ernestask** [comment]
Can’t replicate on master.

**Comment by xsuchy** [comment]
Closing, please reopen if you can reproduce.
