### ISSUE TITLE
Cannot run `abrt status` while another instance of abrt is running

### ISSUE THREAD

**Issue by genodeftest** [abrt/abrt#1535]
Steps to reproduce:
1. Open `abrt-cli bt` and let it analyze a backtrace
2. Before `abrt-cli bt` finishes analyzing the backtrace, run `abrt status --not-reported --quiet`
3. Watch output

Version info:
abrt-2.14.4-7.fc33.x86_64
libreport-2.14.0-13.fc33.x86_64
python3-3.9.0-1.fc33.x86_64

What should happen:
Show status

What happens:
```
connection.py:652:call_blocking:dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Failed: Too many sessions opened

Traceback (most recent call last):
  File "/usr/bin/abrt", line 41, in <module>
    namespace.func(namespace)
  File "/usr/lib/python3.9/site-packages/abrtcli/cli/status.py", line 22, in run
    problems = match_lookup(['*'],
  File "/usr/lib/python3.9/site-packages/abrtcli/match.py", line 72, in match_lookup
    problems = problem.list(auth=authenticate)
  File "/usr/lib64/python3.9/site-packages/problem/__init__.py", line 356, in list
    return [tools.problemify(prob, __proxy) for prob in fun()]
  File "/usr/lib64/python3.9/site-packages/problem/proxies.py", line 91, in list
    return [str(prob) for prob in self._dbus_call('GetProblems')]
  File "/usr/lib64/python3.9/site-packages/problem/proxies.py", line 53, in _dbus_call
    return getattr(self._iface, fun_name)(*args)
  File "/usr/lib64/python3.9/site-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib64/python3.9/site-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib64/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Failed: Too many sessions opened

Local variables in innermost frame:
self: <dbus._dbus.SystemBus (system) at 0x7f0712f0a2c0>
bus_name: dbus.String(':1.160')
object_path: '/org/freedesktop/problems'
dbus_interface: 'org.freedesktop.problems'
method: 'GetProblems'
signature: ''
args: ()
timeout: -1.0
byte_arrays: False
kwargs: {}
get_args_opts: {'byte_arrays': False}
message: <dbus.lowlevel.MethodCallMessage path: /org/freedesktop/problems, iface: org.freedesktop.problems, member: GetProblems dest: :1.160>
```

**Comment by RokeJulianLockhart** [comment]
@genodeftest, works for me with `abrt-2.17.6-4.fc42.x86_64`:

1.	> ~~~sh
	> RokeJulianLockhart@Beedell:~$ abrt bt dae6c51
	> Problem has no backtrace
	> Start retracing process? [y/N] y
	> ~~~

1.	> ~~~sh
	> RokeJulianLockhart@Beedell:~$ abrt status --not-reported --quiet
	> ABRT has detected 4 problems. For more information, run “abrt list”
	> ~~~

**Comment by genodeftest** [comment]
Thanks, I also cannot reproduce it any more. I guess it has been fixed in the meantime.
