### ISSUE TITLE
In notifications, "Please contact the developer" isn't helpful

### ISSUE THREAD

**Issue by allanday** [abrt/abrt#940]
Testing with GNOME 3.15.92 and F22 alpha(ish), notifications for crashed components read:

"Oops!
We're sorry, it looks like <component> crashed. Please contact the developer if you want to report the issue."

The final sentence bothers me: typically there is more than one developer, so it seems inaccurate. But more than that, it's vague. How does someone report the issue? What would they put in that report? It makes it feel like it is the users problem. And really, do we really want to invite every user to manually file a report?

**Comment by hadess** [comment]
This is what happens when the package_name cannot be found. So, yes, we want to request the user to report the bug manually to the "developer" eg. the vendor of the application.

Not sure why the package name cannot be found, which we'll need to fix, and I'd be happy to change the wording.

**Comment by hadess** [comment]
Tested with will_crash, and it seems to work. What was the component crashing?

**Comment by jfilak** [comment]
Kerneloopses sometimes produce such problems. Try `will_oops`.

**Comment by allanday** [comment]
I've corrected the report to include the full text of the message - it was gnome-software in this case. 

Regarding the "Please contact the developer" string - ideally we would suggest that the user submits a microreport through gnome-abrt (probably through a button in the notification).

If a microreport isn't possible, maybe we should point to the distro's bug reporting guidelines? So, instead of "Please contact the developer if you want to report the issue.", show: "Find out <a href="http://fedoraproject.org/wiki/How_to_file_a_bug_report">how to report problems</a>." This changes a directive statement into something a bit more factual.

**Comment by jfilak** [comment]
@allanday What is the output of `rpm -qf /usr/bin/gnome-software`?

**Comment by jfilak** [comment]
I killed gnome-software with and I got this:

"Oops!
We're sorry, it looks like Software crashed.  If you'd like to help resolve the issue, please send a report."

I'm looking forward for the first bugzilla bug mentioning that "Software" shouldn't be capitalized and isn't very informative :D

**Comment by hadess** [comment]
That's weird, why can't abrt find the package name for gnome-software?

"killall -SEGV gnome-software" produces the expected result for me, saying it's been automatically reported.

**Comment by allanday** [comment]
@jfilak ```rpm -qf /usr/bin/gnome-software``` returns ```gnome-software-3.15.92-1.fc22.x86_64```

**Comment by hadess** [comment]
Is auto-reporting enabled or disabled on your machine?

Can you take a screenshot of the Details page for that gnome-software crash?

**Comment by allanday** [comment]
> Is auto-reporting enabled or disabled on your machine?

Enabled.

> Can you take a screenshot of the Details page for that gnome-software crash?

Ah ha! gnome-abrt doesn't run:

[aday@localhost ~]$ gnome-abrt
Namespace(expert=False, problem=None, verbose=None)
/usr/lib64/python3.4/site-packages/gi/overrides/__init__.py:306: Warning: The property GSettings:schema is deprecated and shouldn't be used anymore. It will be removed in a future version.
  return super_init_func(self, **new_kwargs)
(gnome-abrt:2568): Gtk-CRITICAL **: gtk_header_bar_pack: assertion 'gtk_widget_get_parent (widget) == NULL' failed
ERROR:root:local variable 'app' referenced before assignment
Traceback (most recent call last):
  File "/usr/bin/gnome-abrt", line 275, in do_activate
    main_window = OopsWindow(self, self.all_sources, controller)
  File "/usr/lib64/python3.4/site-packages/gnome_abrt/views.py", line 469, in __init__
    self._reload_problems(self._source)
  File "/usr/lib64/python3.4/site-packages/gnome_abrt/views.py", line 700, in _reload_problems
    storage_problems.append(problem_to_storage_values(p))
  File "/usr/lib64/python3.4/site-packages/gnome_abrt/views.py", line 127, in problem_to_storage_values
    app = problem.get_application()
  File "/usr/lib64/python3.4/site-packages/gnome_abrt/problems.py", line 275, in get_application
    self['pid'])
  File "/usr/lib64/python3.4/site-packages/gnome_abrt/application.py", line 39, in find_application
    if not app:
UnboundLocalError: local variable 'app' referenced before assignment

**Comment by jfilak** [comment]
The gnome-abrt problems is fixed in upstream : https://github.com/abrt/gnome-abrt/commit/6b2ca4019c0c43e4e9ea6a5f59871b8286dc9818 and I also pushed that commit to Fedora but that build didn't go to the compose.

Run `abrt-cli list` and `abrt info $id` as root (why root ? because of #938).

**Comment by allanday** [comment]
> Run abrt-cli list and abrt info $id as root (why root ? because of #938).

`abrt-cli list` doesn't return anything.

**Comment by hadess** [comment]
Did you run it as root?

**Comment by allanday** [comment]
> Did you run it as root?

D'oh. I thought that was just for ```abrt-cli list```.

I *think* this is the corresponding report (I've had a number of gnome-software issues, and this is the closest to the time of the notification I saw):

id cb988efb924e216a08d0cc5024d1a81a9946bc99
reason:         gnome-software killed by SIGABRT
time:           Wed 25 Mar 2015 07:10:48 PM GMT
cmdline:        /usr/bin/gnome-software --gapplication-service
package:        gnome-software-3.15.90-3.fc22
uid:            1000 (aday)
count:          2
Directory:      /var/tmp/abrt/ccpp-2015-03-25-19:10:48-2036
Reported:       https://retrace.fedoraproject.org/faf/reports/bthash/6d87b9e896f468582ec4dfa31d2abfdeb5dfdc2b
                https://retrace.fedoraproject.org/faf/reports/579508/
                https://bugzilla.redhat.com/show_bug.cgi?id=1187725
                https://bugzilla.redhat.com/show_bug.cgi?id=1192688

**Comment by jfilak** [comment]
Hmm, but this one has package item. Do you have one without it?

**Comment by allanday** [comment]
> Hmm, but this one has package item. Do you have one without it?

Not that I can see. Here's the complete output of ```abrt-cli list```: http://fpaste.org/203702/44972614/

**Comment by jfilak** [comment]
Well, we have to try to reproduce it. Please start `Software` application, run `killall -ABRT gnome-software` and check if the notification message contains "Software".

**Comment by allanday** [comment]
> Well, we have to try to reproduce it. Please start Software application, run killall -ABRT gnome-software and check if the notification message contains "Software".

I tried this, and the notification correctly referred to "Software".
